apiVersion: v2
name: open-webui
version: 1.0.0
appVersion: "latest"

home: https://www.openwebui.com/
icon: https://itishstudios.net/assert/botg.jpg

description: "Open WebUI: A User-Friendly Web Interface for Chat Interactions 👋"
keywords:
- llm
- chat
- web-ui

sources:
- https://github.com/open-webui/open-webui/tree/main/kubernetes/helm
- https://hub.docker.com/r/ollama/ollama
- https://github.com/open-webui/open-webui/pkgs/container/open-webui

annotations:
  licenses: MIT
